<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>krl</string>
	</array>
	<key>name</key>
	<string>KRL (Kinetic Rule Language)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#global_krl_patterns</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#meta_block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*</string>
					<key>name</key>
					<string>comment.line.krl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.multiline.krl</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|on|off)\b</string>
					<key>name</key>
					<string>constant.language.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(ent:|app:)\b</string>
					<key>name</key>
					<string>constant.language.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(page|event|http|time|location|twitter|facebook|amazon|google|math|meta|oauthmodule|pci):\b</string>
					<key>name</key>
					<string>constant.language.library.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(year|month|week|day|hour|minute|second)s?\b</string>
					<key>name</key>
					<string>constant.language.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b:(JSON|RSS|XML|HTML)\b</string>
					<key>name</key>
					<string>constant.language.krl</string>
				</dict>
			</array>
		</dict>
		<key>escape_sequences</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(b|d|t|n|f|r|\"|\'|\\|\.|w|s|\?|\(|\)|-)</string>
					<key>name</key>
					<string>constant.character.escape.krl</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(all|any|as|avg|capitalize|collect|decode|delete|difference|duplicates|encode|extract|filter|has|head|index|intersection|isnull|join|keys|klog|lc|length|map|max|min|none|notall|once|pairwise|pick|push|put|query|range|reduce|reverse|slice|sort|splice|split|sprintf|substr|sum|tail|trim|typeof|uc|union|unique|values)\b</string>
					<key>name</key>
					<string>support.function.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+\b(after|alert|annotate|append|before|close_notification|content_changed|emit|float_html|float|move_after|move_to_top|noop|notify|percolate|popup|prepend|redirect|replace|replace_html|replace_image_src|replace_inner|send_directive|set_element_attr|sidetab|watch)\b(?=\()</string>
					<key>name</key>
					<string>support.function.web_action.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=page:)(env|url)(?=\()</string>
					<key>name</key>
					<string>support.function.page.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=event:)(env|domain|type|name|attr|attrs|channel|send|get_list|delete|get_history|param)(?=\()</string>
					<key>name</key>
					<string>support.function.event.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=http:)(post|get|put|delete|patch|head)(?=\()</string>
					<key>name</key>
					<string>support.function.http.rkl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=time:)(now|new|add|strftime|atom|compare|timezone|daytime|nighttime|morning|afternoon|evening|night|lunch_time|late_morning|early_afternoon|late_afternoon|time_between|date_between|date_start|day_of_week|today_is|weekday|weekend)(?=\()</string>
					<key>name</key>
					<string>support.function.time.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=location:)(country_code|country_name|region|city|postal_code|latitude|longitude|dma_code|area_code)(?=\()</string>
					<key>name</key>
					<string>support.function.location.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=twitter:)(authorize|authorized|update|friends_timeline|blocking|blocking_ids|favorites|followers_ids|friends_ids|friends_timeline|home_timeline|friendship_exists|mentions|public_timeline|rate_limit_status|retweeted_by_me|retweeted_of_me|retweeted_to_me|retweets|saved_searches|sent_direct_messages|show_friendship|show_saved_search|show_status|show_user|trends_available|trends_location|user_timeline|users_search|trends_daily|trends_weekly)(?=\()</string>
					<key>name</key>
					<string>support.function.twitter.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=facebook:)(authorize|authorized|metadata|picture|search|get|ids)(?=\()</string>
					<key>name</key>
					<string>support.function.facebook.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=amazon:)(item_search|item_lookup)(?=\()</string>
					<key>name</key>
					<string>support.function.amazon.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=google:)(authorize|authorized|get)(?=\()</string>
					<key>name</key>
					<string>support.function.google.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=math:)(random|pi|exp|int|abs|log|sqrt|power|ceiling|floor|round|deg2rad|grad2rad|rad2deg|grad2deg|deg2grad|rad2grad|md5|sha1|hmac_sha1|hmac_sha1_hex|hmac_sha1_base64|hmac_sha256|hmac_sha256_hex|hmac_sha256_base64|tan|sin|cos|cot|sec|csc|atan|asin|acos|acot|asec|acsc|tanh|sinh|cosh|coth|sech|csch|atanh|asinh|acosh|acoth|asech|acsch|great_circle_distance|great_circle_direction|great_circle_midpoint|great_circle_midpoint|great_circle_waypoint)(?=\()</string>
					<key>name</key>
					<string>support.function.math.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=meta:)(rid|version|callingRID|callingVersion|moduleRID|moduleVersion|inModule|host|rulesetName|rulesetAuthor|rulesetDescription|ruleName|eci)(?=\()</string>
					<key>name</key>
					<string>support.function.meta.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=oauthmodule:)(has_token|post|put|get|head|delete|patch|get_auth_url)(?=\()</string>
					<key>name</key>
					<string>support.function.oauthmodule.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=pci:)(new_cloud|delete_cloud|auth|exists|set_password|reset_password|get_username|get_email|list_children|list_parent|set_parent|new_ruleset|delete_ruleset|list_ruleset|new_eci|delete_eci|list_eci|get_eci_attributes|set_eci_attributes|get_eci_policy|set_eci_policy|session_token|create_developer_key|set_permissions|clear_permissions|get_permissions|add_callback|remove_callback|list_callback|add_bootstrap|remove_bootstrap|list_bootstrap|add_appinfo|get_appinfo|remove_appinfo|cloudnumber|set_logging|get_logging|clear_logging|get_logs)(?=\()</string>
					<key>name</key>
					<string>support.function.pci.krl</string>
				</dict>
			</array>
		</dict>
		<key>global_krl_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape_sequences</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#regex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#xdi</string>
				</dict>
			</array>
		</dict>
		<key>html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;&lt;</string>
					<key>end</key>
					<string>&gt;&gt;</string>
					<key>name</key>
					<string>html.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
						<dict>
							<key>match</key>
							<string>#{[^{^}]*}</string>
							<key>name</key>
							<string>string.beesting.krl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>js</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;\|</string>
					<key>end</key>
					<string>\|&gt;</string>
					<key>name</key>
					<string>source.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>key_value_pair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>meta.key-value.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric_constants</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bruleset\b</string>
					<key>name</key>
					<string>keyword.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\s+\b(_api|_rids|after|always|and|at|before|between|cachable|cacheable|callbacks|choose|clear|css|current|dataset|datasource|defaction|dispatch|domain|else|emit|every|failure|fired|for|foreach|forget|from|function|global|history|if|iframe|like|mark|match|not|notfired|null|on|or|pageview|pre|raise|replace(?!\()|rule|schedule|seen|select|set|setting|success|then|web|when|where|with|within)\b</string>
					<key>name</key>
					<string>keyword.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(count|repeat)\b(?=\s+[0-9]+)</string>
					<key>name</key>
					<string>keyword.krl</string>
				</dict>
			</array>
		</dict>
		<key>meta_block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(meta)\b\s*\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.krl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>block.meta.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#global_krl_patterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#meta_block_keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#key_value_pair</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>meta_block_keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(authz|require|logging|sharing|use|module|version|alias|configure|using|name|author|description|key|provide|provides)\b</string>
					<key>name</key>
					<string>keyword.meta.krl</string>
				</dict>
			</array>
		</dict>
		<key>numeric_constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\.\d*\b</string>
					<key>name</key>
					<string>constant.numeric.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\d+\b</string>
					<key>name</key>
					<string>constant.numeric.krl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(eq|neq|cmp)\b</string>
					<key>name</key>
					<string>keyword.operator.krl</string>
				</dict>
			</array>
		</dict>
		<key>regex</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bre/.*/[gim]{0,3}</string>
					<key>name</key>
					<string>string.regexp.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bre#.*#[gim]{0,3}</string>
					<key>name</key>
					<string>string.regexp.krl</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape_sequences</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escape_sequences</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>xdi</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;\[</string>
					<key>end</key>
					<string>\]&gt;</string>
					<key>name</key>
					<string>source.xdi</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.krl</string>
	<key>uuid</key>
	<string>fc2e9679-a431-4503-a18c-9d4f53a72830</string>
</dict>
</plist>
