<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>krl</string>
	</array>
	<key>name</key>
	<string>KRL (Kinetic Rule Language)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(ruleset)\b\s\b([A-z_][A-z0-9_]*)|([0-9]*)\b\s\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.krl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.ruleset.krl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>block.ruleset.krl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(meta)\b\s\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.krl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>block.meta.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#angleQuotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#metaKeywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#metaConstants</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(dispatch)\b\s\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.krl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>block.dispatch.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dispatchKeywords</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(global)\b\s\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.krl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>block.global.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numericConstant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#globalKeywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#globalConstants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#formatConstants</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(rule)\b\s([A-z0-9_]+)\s\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.krl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.rule.krl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>name</key>
					<string>block.rule.krl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quotedString</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#eventexKeywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#eventexConstants</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functions</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#formatConstants</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(pre)\b\s\{</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.krl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>block.rule.pre.krl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\b[A-z0-9_]+\b\s=\s(function)\s*\(.*\)\s\{</string>
									<key>beginCaptures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>storage.type.function.krl</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\}</string>
									<key>name</key>
									<string>block.rule.pre.function.krl</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#functions</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#operators</string>
										</dict>
									</array>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(if)\b\s.*\s(then)\s\{</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.krl</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.krl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>block.rule.if.krl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numericConstant</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#quotedString</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#functions</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#operators</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b(always|fired|notfired|else)\b</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.krl</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>name</key>
							<string>block.rule.postlude.krl</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numericConstant</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#postludeKeywords</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ent:|app:|page:|datasource:|dataset:)\b</string>
			<key>name</key>
			<string>constant.other.krl</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>angleQuotedString</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;&lt;</string>
					<key>end</key>
					<string>&gt;&gt;</string>
					<key>name</key>
					<string>string.quoted.angle.krl</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*\n</string>
					<key>name</key>
					<string>comment.line.krl</string>
				</dict>
			</array>
		</dict>
		<key>dispatchKeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bdomain\b</string>
					<key>name</key>
					<string>keyword.dispatch.krl</string>
				</dict>
			</array>
		</dict>
		<key>eventexConstants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false|ent:|app:|page:)\b</string>
					<key>name</key>
					<string>constant.other.eventex.krl</string>
				</dict>
			</array>
		</dict>
		<key>eventexKeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(select|when|setting)\b</string>
					<key>name</key>
					<string>keyword.eventex.krl</string>
				</dict>
			</array>
		</dict>
		<key>formatConstants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:(JSON|XML|RSS)\b</string>
					<key>name</key>
					<string>constant.other.format.krl</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(extract|notify|match|head)\b</string>
					<key>name</key>
					<string>support.function.krl</string>
				</dict>
			</array>
		</dict>
		<key>globalConstants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(year|month|week|day|hour|minute|second)s\b</string>
					<key>name</key>
					<string>constant.other.global.krl</string>
				</dict>
			</array>
		</dict>
		<key>globalKeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(dataset|datasource|cachable|for)\b</string>
					<key>name</key>
					<string>keyword.global.krl</string>
				</dict>
			</array>
		</dict>
		<key>metaConstants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(on|off)\b</string>
					<key>name</key>
					<string>constant.other.meta.krl</string>
				</dict>
			</array>
		</dict>
		<key>metaKeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(name|author|description|logging|sharing|use|provide|configure|key)\b</string>
					<key>name</key>
					<string>keyword.meta.krl</string>
				</dict>
			</array>
		</dict>
		<key>numericConstant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string> \d+</string>
					<key>name</key>
					<string>constant.numeric.krl</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(with|neq|eq)\b</string>
					<key>name</key>
					<string>keyword.operator.krl</string>
				</dict>
			</array>
		</dict>
		<key>postludeKeywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(set)\b</string>
					<key>name</key>
					<string>keyword.postlude.krl</string>
				</dict>
			</array>
		</dict>
		<key>quotedString</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.krl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.krl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>re/.*/</string>
					<key>name</key>
					<string>string.regexp.classic.krl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.krl</string>
	<key>uuid</key>
	<string>fc2e9679-a431-4503-a18c-9d4f53a72830</string>
</dict>
</plist>
